default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development
  username: postgres
  password: 123
  template: template0

test:
  <<: *default
  database: myapp_test
  username: postgres
  password: 123
  template: template0

production:
  <<: *default
  database: myapp_production
  username: postgres
  password: 123
